### ISSUE TITLE
I'm working on a successor to click-thru-prototype Sketch plugin

### ISSUE THREAD

**Issue by markhorgan** [markhorgan/click-thru-prototype#12]
@ChadNicholas, @idsampaio, @carthikeyan, @XOP, @ehausen

I'm working on a successor to the click-thru-prototype Sketch plugin. It will allow transitions between artboards and will have a GUI within Sketch similar to Adobe XD. I'm looking for beta users so if you're interested in trying it out you can add your email to the [mailing list here](http://protowire.com).

**Comment by ColinLondon** [comment]
Can we have it link to artboards on other pages?

**Comment by markhorgan** [comment]
Thanks for the feature request. I'll consider adding it.

**Comment by hellmachine2000** [comment]
Hi Mark, just wanted to say this plugin works awesome, straight forward and creates static files,. keep it up!

**Comment by pedrosimao** [comment]
Still looking for beta testers?

**Comment by markhorgan** [comment]
@pedrosimao No, I'm no longer looking for beta testers - I released it a year ago. You can try it out [here](https://protowire.com) if you want.
