### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by davej** [markhorgan/click-thru-prototype#3]
Using Sketch 41.2 (35397).

The plugin seemed to install correctly and I can see the menu options under `Plugins > Click-Thru Prototype` but clicking on the menu items doesn't do anything. I tried all of the menu items and I tried them with lots of different elements highlighted on the canvas but nothing happens (no error either).

**Comment by markhorgan** [comment]
Looks like it's an issue on MacOS Sierra - the current version of the JS engine doesn't like `const`. It's now fixed.
