### ISSUE TITLE
export deletes and overwrite?

### ISSUE THREAD

**Issue by vixaysys** [markhorgan/click-thru-prototype#5]
Tried out the plugin and did an export to html file to desktop and it seems like that wiped all the files on my desktop.

**Comment by markhorgan** [comment]
I'm really sorry about that. Before it generates the files it deletes all the files in the directory it's exporting to - the idea being you can export multiple times and not have old files lying around. 

**I have now changed it so it doesn't delete any files** - just overwrites the existing ones. You will need to re-download the zip file and double click on `Click-Thru Prototype.sketchplugin` to update the plugin. When you go to `Export to HTML`, click on `New Folder` in the file dialog and then click on `Export` to export into the new folder - this will make sure that no existing files will be overwritten.

**Comment by vixaysys** [comment]
thanks for the fix @markhorgan!  Now onto file recovery.  Lol
